# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the “License”);
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an “AS IS” BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: 'Build and deploy'

on:
  schedule:
    # Run daily at 06:05 UTC (07:05 CET / 08:05 CEST)
    # and 18:05 UTC (19:05 CET / 20:05 CEST).
    - cron: '05 06,18 * * *'
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-website:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: npm install

      - name: Update website
        run: npm run find && npm run render

      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          single-commit: true
          git-config-name: Chrome for Testing bot
          git-config-email: mathias+cft@chromium.org
